In [90]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print(pd.__version__)

2.2.0

Sumber: https://www.kaggle.com/datasets/ashtired11/cattle-diseases

In [91]:
# data_sapi_yang_pernah_terinfeksi = 'vg_cattle.csv'
# df = pd.read_csv(data_sapi_yang_pernah_terinfeksi)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)
# df

In [92]:
print("Data statistik deskriptif sapi yang pernah terkena penyakit:")
df.describe()

Data statistik deskriptif sapi yang pernah terkena penyakit:

,adm1cd,adm1nm,Tick Borne Infected,Tick Borne Treated,Tick Borne Recovered,Died of Tick Borne,CBPP Infected,CBPP Treated,CBPP Recovered,Died of CBPP,Trypanosomiasis Infected,Trypanosomiasis Treated,Trypanosomiasis Recovered,Died of Trypanosomiasis,Lumpy Skin Infected,Lumpy Skin Treated,Lumpy Skin Recovered,Died of Lumpy Skin,Helmenthioitis Infected,Helmenthioitis Treated,Helmenthioitis Recovered,Died of Helmenthioitis,Foot Mouth (FMD) Infected,Foot Mouth (FMD) Treated,Foot Mouth (FMD) Recovered,Died of Foot Mouth (FMD),Brucellosis Infected,Brucellosis Treated,Brucellosis Recovered,Died of Brucellosis,Black Quarter Infected,Black Quarter Treated,Black Quarter Recovered,Died of Black Quarter,Total Infected,Total Treated,Total Recovered,Total Died
count,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31
unique,31,31,31,31,31,29,31,31,30,30,30,30,30,21,31,31,31,28,31,31,31,25,31,31,31,28,30,30,30,24,26,26,26,25,31,31,31,31
top,TZA001,Arusha,"365,918","362,436","355,970",0,"315,681","300,427",0,0,0,0,0,0,"129,323","125,510","116,556",0,"333,918","327,618","323,639",0,"311,204","294,127","280,200",0,0,0,0,0,0,0,0,0,"1,748,347","1,713,695","1,545,409","183,705"
freq,1,1,1,1,1,3,1,1,2,2,2,2,2,11,1,1,1,4,1,1,1,7,1,1,1,4,2,2,2,8,6,6,6,7,1,1,1,1

Sumber: https://data.apps.fao.org/catalog/dataset/small-scale-cattle-diseases-infection-occurrence-tanzania-adm1-2019-20-nbs/resource/57f02a52-f031-4aef-9062-2caa20ef6f5d

In [93]:
data_sapi_yang_pernah_terinfeksi_di_afrika = 'small-scale-cattle-diseases-infection-occurence.csv'
df = pd.read_csv(data_sapi_yang_pernah_terinfeksi_di_afrika)
df

,adm1cd,adm1nm,Tick Borne Infected,Tick Borne Treated,Tick Borne Recovered,Died of Tick Borne,CBPP Infected,CBPP Treated,CBPP Recovered,Died of CBPP,Trypanosomiasis Infected,Trypanosomiasis Treated,Trypanosomiasis Recovered,Died of Trypanosomiasis,Lumpy Skin Infected,Lumpy Skin Treated,Lumpy Skin Recovered,Died of Lumpy Skin,Helmenthioitis Infected,Helmenthioitis Treated,Helmenthioitis Recovered,Died of Helmenthioitis,Foot Mouth (FMD) Infected,Foot Mouth (FMD) Treated,Foot Mouth (FMD) Recovered,Died of Foot Mouth (FMD),Brucellosis Infected,Brucellosis Treated,Brucellosis Recovered,Died of Brucellosis,Black Quarter Infected,Black Quarter Treated,Black Quarter Recovered,Died of Black Quarter,Total Infected,Total Treated,Total Recovered,Total Died
0,TZA001,Arusha,"365,918","362,436","355,970","16,082","315,681","300,427","234,108","83,231","247,040","259,309","196,637","53,885","129,323","125,510","116,556","5,471","333,918","327,618","323,639","4,145","311,204","294,127","280,200","14,424","34,320","33,491","29,346","4,642","10,943","10,777","8,953","1,824","1,748,347","1,713,695","1,545,409","183,705"
1,TZA002,Dar-es-salaam,424,424,424,0,424,424,424,0,"3,388","3,388","3,388","1,059",424,424,424,0,847,847,847,0,0,0,0,0,"1,059","1,059",847,212,0,0,0,0,"6,565","6,565","6,353","1,271"
2,TZA003,Dodoma,"274,264","261,482","261,482","12,782","278,282","273,169","221,676","56,971","74,135","73,040","67,927","5,478","95,682","78,518","75,961","17,895","113,577","112,481","108,464","1,826","324,662","286,316","304,941","14,243","13,878","12,782","11,321","2,191","9,495","5,478","7,304","2,556","1,183,975","1,103,266","1,059,077","113,942"
3,TZA004,Geita,"105,422","106,648","99,702","6,129","83,357","81,723","64,970","15,527","22,474","22,474","17,570","4,903","77,228","85,809","69,056","4,903","282,761","340,375","263,556","10,215","205,124","220,243","166,306","28,603","28,194","26,151","21,657","6,538","5,312","2,860","1,634","3,678","809,873","886,284","704,450","80,497"
4,TZA005,Iringa,"41,847","51,277","39,489","2,947","12,967","14,735","9,430","3,536","17,682","19,450","14,735","2,947","30,059","20,039","28,880","1,179","93,713","96,071","67,190",0,"120,235","124,361","115,520","4,715","2,358","1,768","1,768",589,"8,251","8,251","7,662",589,"327,111","335,952","284,675","16,503"
5,TZA006,Kagera,"121,125","137,431","111,808","3,494","43,093","29,117","31,446","8,153","33,775","33,775","33,775",0,"103,655","103,655","86,185","1,165","173,535","165,383","161,889","6,988","266,708","258,556","250,403","8,153","16,305","11,647","11,647","1,165",0,0,0,0,"758,198","739,563","687,153","29,117"
6,TZA007,Kaskazini Pemba,"2,975","2,082","2,528",149,"5,652","4,462","4,016",892,0,0,0,0,"5,652","6,098","5,354",892,"22,904","22,161","19,484","1,636",744,744,446,297,0,0,0,0,595,446,149,446,"38,521","35,992","31,977","4,313"
7,TZA008,Kaskazini Unguja,"5,830","5,743","5,482",87,609,522,435,174,174,174,174,0,"4,785","4,176","4,089",174,"5,308","5,395","4,785",261,"5,569","4,785","4,959",435,870,609,783,174,"2,958","2,610","2,001",870,"26,103","24,014","22,709","2,175"
8,TZA009,Katavi,"18,121","18,121","17,503","1,853","60,335","60,335","46,332","35,212","10,708","10,708","10,296",0,"19,768","19,357","12,767","6,384","17,091","15,856","14,414","1,853","49,215","39,743","43,037","5,148","1,236","1,236","1,236",0,"1,030","1,030",824,206,"177,503","166,384","146,409","50,656"
9,TZA010,Kigoma,"105,671","105,671","103,714","1,957","107,628","107,628","96,865","10,763","38,159","38,159","38,159",0,"38,159","37,181","35,224","1,957","136,002","115,455","71,426","7,827","143,830","140,895","136,002","6,849","13,698","13,698","13,698",0,0,0,0,0,"583,147","558,686","495,088","29,353"
10,TZA011,Kilimanjaro,"219,654","211,214","202,996","17,990","161,242","155,468","140,587","24,431","256,077","212,102","169,238","69,294","37,979","30,871","28,873","3,554","285,172","280,508","280,952","1,555","208,771","196,111","170,792","9,106","63,298","58,634","45,086","15,547","4,220","4,220","3,331",666,"1,236,412","1,149,128","1,041,855","142,142"
11,TZA012,Kusini Pemba,"6,895","8,216","6,749",147,"1,614","1,174","1,027",587,0,0,0,0,"8,949","8,216","6,895",880,"9,829","9,829","9,389",440,880,440,587,293,"1,614","1,027","1,467",0,0,0,0,0,"29,782","28,902","26,114","2,347"
12,TZA013,Kusini Unguja,"6,829","6,829","6,201",628,628,706,549,78,235,235,235,0,"5,337","5,416","5,102",157,"7,221","7,300","7,143",78,235,235,157,78,157,78,78,78,"1,256","1,020",549,549,"21,899","21,820","20,015","1,648"
13,TZA014,Lindi,"9,397","16,445","9,397",0,0,0,0,0,"72,357","72,357","72,357",0,0,0,0,0,"14,096","14,096","14,096",0,940,940,940,0,"1,879","1,879","1,879",0,0,0,0,0,"98,669","105,717","98,669",0
14,TZA015,Manyara,"134,447","132,763","121,459","8,418","709,514","193,854","143,346","73,357","171,005","145,511","128,915","30,786","184,474","154,169","135,649","27,419","202,512","196,259","184,714","3,127","289,337","274,666","265,046","5,772","11,785","13,709","10,823","1,684","8,899","8,899","5,772","3,127","1,711,973","1,119,830","995,725","153,688"
15,TZA016,Mara,"291,786","293,170","276,837","4,983","70,593","66,164","54,814","15,226","93,571","90,249","84,435","6,367","143,678","140,080","133,712","4,429","550,629","541,493","540,109","4,983","284,588","252,475","255,797","7,198","13,565","11,904","11,350",554,"11,073","8,582","5,537","5,537","1,459,485","1,404,117","1,362,592","49,277"
16,TZA017,Mbeya,"108,114","124,895","96,560","13,480","111,140","166,160","64,098","41,265","33,837","27,785","9,078","8,803","63,548","116,642","51,994","11,004","151,579","188,443","128,471","7,428","137,824","184,866","132,598","7,978","13,480","11,279","8,803","2,476","18,982","20,907","17,606","1,926","638,504","840,976","509,207","94,359"
17,TZA018,Mjini Magharibi,"3,836","3,949","3,724",113,"1,918","1,805","1,241",677,339,339,339,0,"5,078","5,078","4,852",339,"13,428","10,268","9,478",0,"4,175","4,175","4,175",0,677,564,564,113,"2,708","2,708",339,113,"32,158","28,886","24,711","1,354"
18,TZA019,Morogoro,"150,054","148,267","138,145","8,336","225,080","226,867","181,017","47,041","98,249","98,249","91,104","10,718","106,586","105,395","99,440","11,909","105,395","105,395","100,631",0,"259,021","259,021","254,258","14,886","29,177","20,245","17,268","10,123","19,054","19,054","14,291","4,168","992,617","982,494","896,154","107,181"
19,TZA020,Mtwara,"44,243","74,755","44,243",0,"9,154","21,359",0,"3,051","7,628","7,628","7,628",0,"9,154","21,359","9,154",0,"9,154","9,154","9,154",0,"3,051","3,051","3,051",0,0,0,0,0,0,0,0,0,"82,383","137,306","73,230","3,051"
20,TZA021,Mwanza,"225,974","225,578","214,101","2,770","74,797","64,903","46,699","22,162","20,975","14,247","7,519","12,664","50,656","45,511","37,992","2,770","306,707","301,958","288,503","12,268","110,019","106,853","100,917","7,519","6,332","5,145","2,770","1,187","9,498","9,498","6,728","2,770","804,958","773,693","705,228","64,112"
21,TZA022,Njombe,"20,886","20,113","18,952","1,160","5,028","4,255","1,547","1,160",774,774,774,0,"15,084","15,471","15,084",0,"30,943","31,329","26,688",0,"37,905","39,452","37,131","1,160",774,387,387,387,"35,197","37,131","10,443",774,"146,590","148,911","111,006","4,641"
22,TZA023,Pwani,"409,825","416,464","399,646","2,877","365,125","389,245","344,767","19,031","97,367","104,448","86,524","6,196","44,036","133,879","33,636","10,401","127,241","139,854","126,798",443,"150,697","153,131","150,697",221,"14,162","13,277","13,720",221,"313,786","3,983","3,098",885,"1,522,240","1,354,282","1,158,885","40,274"
23,TZA024,Rukwa,"94,103","95,675","87,227","7,858","60,313","62,670","45,971","11,198","8,448","8,448","7,858",589,"58,937","59,134","54,812","3,929","53,830","53,044","49,507","4,126","68,957","74,065","66,796",786,"2,554","2,161","2,161",0,"2,750","2,750","2,357",196,"349,892","357,947","316,691","28,683"
24,TZA025,Ruvuma,"77,960","73,708","73,708","2,835","24,097","23,388","14,175","8,505","19,136","19,136","10,631","8,505","41,106","51,029","36,145","4,252","60,242","60,242","55,990","8,505","6,379","6,379","3,544","2,126","1,417","1,417",709,0,"19,844","19,844","14,883","4,961","250,181","255,143","209,784","39,689"
25,TZA026,Shinyanga,"364,340","358,312","353,856","7,339","125,815","117,428","94,099","38,007","25,949","25,687","24,115","1,835","48,753","47,181","41,938","5,504","83,353","74,703","66,577","11,009","179,549","166,443","155,697","15,465","5,242","4,456","4,718",262,"9,698","13,892","1,835","7,863","842,701","808,102","742,835","87,284"
26,TZA027,Simiyu,"258,146","234,012","226,691","18,168","85,958","78,366","72,942","16,812","9,762","9,219","7,864","1,898","110,363","108,465","91,381","16,812","36,336","44,742","32,811","6,508","399,150","378,270","359,289","10,304","11,118","9,762","10,033","1,627","3,796",813,813,271,"914,628","863,649","801,825","72,400"
27,TZA028,Singida,"290,005","289,639","254,531","37,668","88,866","86,672","79,724","9,508","61,804","61,439","59,976",366,"88,866","84,112","85,575","2,194","132,385","132,385","129,094","5,120","346,323","315,604","336,449","29,256","14,628","6,948","7,314","6,217","20,480","20,480","20,480",0,"1,043,358","997,280","973,143","90,329"
28,TZA029,Songwe,"36,644","30,684","28,035","2,428","42,163","42,825","28,697","11,479","2,428","1,766","1,766",662,"39,073","30,684","29,360","10,154","35,761","34,216","31,126","4,856","22,075","21,633","19,647","1,545","2,870","1,545","2,207",441,"31,567","26,269","26,269","5,298","212,582","189,624","167,108","36,865"
29,TZA030,Tabora,"258,422","250,864","232,260","69,184","256,969","309,874","156,681","110,752","24,418","21,802","20,058","3,198","206,389","202,610","163,948","40,406","136,042","131,682","118,601","20,058","202,901","193,599","170,053","20,639","17,732","17,151","7,558","3,779","83,428","79,939","65,114","16,279","1,186,300","1,207,521","934,273","284,294"
30,TZA031,Tanga,"306,388","291,563","282,738","13,413","188,845","188,492","150,017","36,004","233,321","257,323","201,905","41,299","61,772","60,713","58,595","5,295","340,980","335,685","330,037","4,236","157,077","156,018","147,899","8,825","69,184","41,652","67,066","2,824","16,590","16,590","15,531","1,412","1,374,156","1,348,035","1,253,789","113,307"